# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_area', '0002_auto_20161115_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
