# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_area', '0003_registration_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='pago'),
        ),
    ]
