# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_area', '0004_auto_20161115_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cnpj',
            field=models.CharField(default='', max_length=16, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
    ]
