# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArduinoSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arduino_account_rfid', models.CharField(default='ACbcad883c9c3e9d9913a715557dddff99', max_length=255)),
                ('arduino_auth_token', models.CharField(default='abd4d45dd57dd79b86dd51df2e2a6cd5', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações do arduino',
            },
        ),
    ]
